config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'

  devise_for :users
  
  resources :users do
    resources :tweets
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :body, :presence => true
  validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets

  validates_presence_of :username

  def email_required?
    false
  end

  # attr_accessible :username, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit :username, :password, :password_confirmation
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def show
    @user = User.find(params[:user_id])
    @tweet = @user.tweets
  end

  def new
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.new
  end

  def create
    @user = User.find(params[:user_id])
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.js { flash.now[:notice] = "Thanks for tweeting!" }
        # flash.now necessary for AJAX loading
        # of notification and not having it persist through html requests
      end
    else
      render :new
    end
  end


private
  def tweet_params
    params.require(:tweet).permit(:body, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @users = User.all
    @tweets = Tweet.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Updated user information!"
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(current_user)
    @user.tweets.destroy
    @user.destroy
    redirect_to '/'
  end

private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">

    <% if user_signed_in? %>
      <li><%= link_to 'Home', users_path %></li>
      <li><%= link_to 'Your profile', user_path(current_user) %></li>
      <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Home', users_path %></li>
      <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <li><%= link_to 'Login', new_user_session_path %></li>
    <% end %>

  </ul>

  <% if user_signed_in? %>
    <p class="float-nav">
      Logged in as <strong><%= current_user.username %></strong>.
    </p>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Two Tone Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/navbar' %>

    <div id="flash">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/shared/_header.html.erb
<h1><%="#{title}"%></h1>

app/views/tweets/_form.html.erb
<%= bootstrap_form_for [@user, @tweet], remote: true do |f| %>
  <%= f.text_field :body %>
  <%= f.submit "Tweet!" %>
<%end%>

app/views/tweets/_tweet.html.erb
<ul>
  <li><h5><%= link_to tweet.user.username, user_path(tweet.user) %></h5></li>
    <ul>
      <li><p><%= tweet.body %></p></li>
    </ul>
</ul>

app/views/tweets/create.js.erb
$('#new_tweet').remove();
$('#new_tweet_link').show();
$('#tweets').prepend('<p><%= j @tweet.body %></p>');
$('#flash').html('<%= j flash[:notice] %>');
// #flash targets the div surrounding the notices, and the erb
// renders the notice laid out in the controller

app/views/tweets/new.js.erb
$('#new_tweet_link').hide().after('<%= j render("form") %>')

app/views/users/_tweets.html.erb
<h1><%= @user.username %>'s Tweets</h1>

<div id="tweets">
  <% @user.tweets.reverse.each do |tweet| %>
    <p><%= tweet.body %></p>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/header', title: "Two Tone Twitter" %>

<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'shared/header', title: "Two Tone Twitter" %>

<% if @tweets.any? %>

  <h3>All Tweets</h3>

  <%= render @tweets.reverse %>

<% else %>

  <h3>No tweets exist yet. Become the first user to tweet!</h3>

<% end %>

app/views/users/new.html.erb
<h1>New user
</h1>

<% if @list.errors.any? %>
<h3>Oops there were some errors. Please try again:</h3>
<ul>
  <% @list.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= bootstrap_form_for @list do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/header', title: "Two Tone Twitter" %>

<% if (user_signed_in?) && (current_user.id == @user.id) %>
  <%= link_to "Tweet away!", new_user_tweet_path(@user), id: "new_tweet_link", remote: true %>
<% else %>
  <h5>Thanks for checking out <%= @user.username %>'s page!</h5>
<% end %>

<%= render "tweets" %>